name: taskmanager

services:
  postgres:
    image: postgres:16-alpine
    container_name: taskmanager-db
    environment:
      POSTGRES_USER: rup
      POSTGRES_PASSWORD: tmpassword
      POSTGRES_DB: taskboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rup -d taskboard"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  user-service:
    build: ./user-service
    image: taskmanager-user:local
    container_name: user-service
    environment:
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: taskboard
      PGUSER: rup
      PGPASSWORD: tmpassword
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  task-service:
    build: ./task-service
    image: taskmanager-task:local
    container_name: task-service
    environment:
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: taskboard
      PGUSER: rup
      PGPASSWORD: tmpassword
      USER_SERVICE_URL: http://user-service:3001
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started

  frontend:
    build: ./frontend
    image: taskmanager-frontend:local
    container_name: tb-frontend
    ports:
      - "8080:80"
    depends_on:
      user-service:
        condition: service_started
      task-service:
        condition: service_started

volumes:
  pgdata:
