spring.application.name=task-service

server.port=5000

spring.datasource.url=jdbc:postgresql://localhost:5432/taskboard
spring.datasource.username=rup
spring.datasource.password=tmpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
